version: "3"

services:
  
  portainer:
    image: "portainer/portainer"
    restart: unless-stopped
    environment:
      - VIRTUAL_HOST=$VIRTUAL_HOST
      - LETSENCRYPT_HOST=$VIRTUAL_HOST
      - LETSENCRYPT_EMAIL=$LETSENCRYPT_EMAIL
      - LETSENCRYPT_ENABLED=1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data:/data
    networks:
      - tier_0
      - tier_3

  watchtower:
    image: "containrrr/watchtower"
    environment:
      - WATCHTOWER_CLEANUP=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --schedule "3 0 * * * *"

networks:
  tier_2: null
  tier_3: null
  tier_0:
    external:
      name: network_tier_0
  tier_1:
    external:
      name: network_tier_1
