version: "3"

networks:
  tier_0: ## Outside world
  tier_1: ## Inside proxy
  tier_log: ## Logging

volumes:
  nginx_:
  vhost_:
  certs_:
  letsencrypt_:

services:

  ###########
  ## PROXY ##
  ###########
  nginx:
    image: ${REGISTRY}/nginx:latest
    build: images/nginx
    container_name: $COMPOSE_PROJECT_NAME.nginx
    restart: unless-stopped
    environment:
      - LOGSTASH_TAGS="loadbalancer,proxy"
    labels:
        com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: "true"
    ports:
      - "80:80"
      - "443:443"
    networks:
      - tier_0
      - tier_1
      - tier_log
    volumes:
      - vhost_:/etc/nginx/vhost.d
      - nginx_:/etc/nginx/conf.d
      - letsencrypt_:/usr/share/nginx/html
      - certs_:/etc/nginx/certs:ro

  dockergen:
    image: ${REGISTRY}/dockergen:latest
    build: images/dockergen
    container_name: $COMPOSE_PROJECT_NAME.dockergen
    restart: unless-stopped
    environment:
      - LOGSTASH_TAGS="loadbalancer,proxy"
    entrypoint: /usr/local/bin/docker-gen -notify-sighup $COMPOSE_PROJECT_NAME.nginx -watch -wait 5s:30s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
    networks:
      - tier_1
      - tier_log
    volumes:
      - vhost_:/etc/nginx/vhost.d
      - nginx_:/etc/nginx/conf.d
      - letsencrypt_:/usr/share/nginx/html
      - certs_:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro

  letsencrypt:
    image: ${REGISTRY}/letsencrypt:latest
    depends_on:
      - nginx
      - dockergen
    build: images/letsencrypt
    container_name: $COMPOSE_PROJECT_NAME.letsencrypt
    restart: unless-stopped
    networks:
      - tier_0
      - tier_1
      - tier_log
    volumes:
      - vhost_:/etc/nginx/vhost.d
      - nginx_:/etc/nginx/conf.d
      - letsencrypt_:/usr/share/nginx/html
      - certs_:/etc/nginx/certs:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - LOGSTASH_TAGS="loadbalancer,proxy"
      - NGINX_DOCKER_GEN_CONTAINER=$COMPOSE_PROJECT_NAME.dockergen
      - NGINX_PROXY_CONTAINER=$COMPOSE_PROJECT_NAME.nginx
