version: "3"

volumes:
  elasticsearch_:

services:
  #############
  ## Logging ##
  #############
  logspout:
    image: ${REGISTRY}/logspout:latest
    container_name: $COMPOSE_PROJECT_NAME.logspout
    build: ./images/logspout
    env_file:
      - .env.elk
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - tier_log
    depends_on:
      - logstash
      - kibana
    restart: unless-stopped

  elasticsearch:
    image: ${REGISTRY}/elasticsearch:latest
    container_name: $COMPOSE_PROJECT_NAME.elasticsearch
    restart: unless-stopped
    volumes:
      - elasticsearch_:/usr/share/elasticsearch/data
    build:
      context: ./images/elasticsearch/
      args:
        ELK_VERSION: $ELK_VERSION
    env_file:
      - .env.elk
    networks:
      - tier_log

  logstash:
    image: ${REGISTRY}/logstash:latest
    container_name: $COMPOSE_PROJECT_NAME.logstash
    restart: unless-stopped
    build:
      context: ./images/logstash/
      args:
        ELK_VERSION: $ELK_VERSION
    environment:
      - xpack.monitoring.elasticsearch.password=${ELASTIC_PASSWORD}
      - xpack.monitoring.elasticsearch.username=logstash_system
    env_file:
      - .env.elk
    networks:
      - tier_log
    depends_on:
      - elasticsearch
      - elk_starter

  kibana:
    image: ${REGISTRY}/kibana:latest
    container_name: $COMPOSE_PROJECT_NAME.kibana
    restart: unless-stopped
    build:
      context: ./images/kibana/
      args:
        ELK_VERSION: $ELK_VERSION
    environment:
      - VIRTUAL_HOST=localhost
      - ELASTICSEARCH_USERNAME=kibana
      - ELASTICSEARCH_PASSWORD=${ELASTIC_PASSWORD}
      - elasticsearch.username=elastic
      - elasticsearch.password=${ELASTIC_PASSWORD}
    env_file:
      - .env.elk
    networks:
      - tier_log
    depends_on:
      - elasticsearch
      - logstash
      - elk_starter

  elk_starter:
    image: ${REGISTRY}/elk_starter:latest
    container_name: $COMPOSE_PROJECT_NAME.elk_starter
    build:
      context: ./images/elk_starter/
    env_file:
      - .env.elk
    networks:
      - tier_log
    depends_on:
      - elasticsearch